<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsTestProject>true</IsTestProject>
        <XunitStartupFullName>Startup</XunitStartupFullName>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="AutoFixture.Xunit3" Version="4.19.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
        <PackageReference Include="coverlet.collector" Version="3.2.0">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Xunit.DependencyInjection" Version="11.1.1" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3" Version="3.2.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\EaFramework\EaFramework.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Update="xunit.v3.core.mtp-v1" ExcludeAssets="all" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Update="xunit.v3.core.mtp-v1" ExcludeAssets="all" />
        <PackageReference Update="xunit.v3.mtp-v1" ExcludeAssets="all" />
        <PackageReference Update="xunit.v3.runner.inproc.console" ExcludeAssets="all" />
    </ItemGroup>

</Project>
